namespace DAL.BlogApp.EF
{
    public class TextInitializer
    {

        public static string ribeye = @"Often the crown jewel of the steakhouse menu, a well-prepared ribeye steak is a beautiful thing. We spoke with Dino Tsaknis, Executive Chef at David Burke's Primehouse at The James Chicago, about what makes it uniquely delicious, and how the amateur cook can tackle it at home.
The ribeye comes from the loin muscle (longissimus dorsi), a long muscle that stretches along the spine from the base of the neck to the hip, outside of the rib cage. They are cut from the top of the muscle, just behind the shoulder (followed, as you travel down the spine, by the strip and the porterhouse). As a little-used part, steaks from the loin are particularly tender, but Tsaknis prefers the ribeye to the strip. As he says, ""the ribeye has a more decadent flavoring of richness and butteriness, whereas the Kansas City strip features more of a straightforward meat flavor.""
He goes on to explain that the ribeye\'s high-fat content ""offers generous marbling, and therefore, the meat has more moisture to cook with. Where the flavor comes from in a good piece of meat is from the fat, and no other cut of meat has the amount of fat that a ribeye does.""
If you're up for preparing a ribeye at home, especially if it's your first time, Tsaknis advises buying a 30-oz ribeye and sharing it with one or two people rather than buying thinner individual steaks. ""The thicker the steak, the friendlier it is to the home cook,"" as thin steaks cook faster and can easily be overcooked.Always get a bone-in steak — the bone not only adds flavor, but also effectively bastes the steak from the inside during cooking as the moisture in the bone evaporates.And look for good marbling, Tsaknis says, ""
in the eye or center of the ribeye, the red meat should be dotted with little white dots of fat evenly distributed throughout the muscle (this is not the same as large fat deposits between muscles).";

        public static string run = @"Running is an effective way to help increase your fitness levels, burn fat and lose weight. And it can be more convenient and cost-effective, and less time-consuming, than going to the gym. While running anytime can help you toward your fitness and fat-loss goals, running in the morning may provide extra psychological and physiological benefits that help speed your progress.
Lower Blood Pressure
Early morning exercise has a positive effect on blood pressure, according to Dr. Scott Collier at Appalachian State University. Collier tracked the blood pressure and sleep patterns of three groups of 40 to 60 year old participants who walked on a treadmill at 7 a.m., 1 p.m. and 7 p.m. The early morning exercisers experienced an average drop of 10 percent in their blood pressure, which lasted all day, and a 25 percent drop at night. If your blood pressure tends toward the high side, your early morning run may have positive long-term benefits to your health.
Stress Relief
Many runners often cite one benefit of running as stress relief -- a long run on your own with no distractions can be a beneficial way to take your mind off the pressures of work and family life, and help you relax. Personal trainer Christian Finn advises that getting your cardio out of the way first thing in the morning gives you the feeling of being one step closer to your goals, and it helps you stay in a positive mood for the rest of the day.
Convenience
Even the most dedicated exercisers often say they don't have time to work out, and that work, family and social commitments can take precedence over training. If you often find yourself having to stay late at work or attend various social events in the evening, then training in the morning is a way to include exercise in your schedule.
Weight Training
Running can help you lose fat and improve your body composition, but exercise programs should also include resistance training to help build lean muscle and burn fat. Charles Poliquin, owner of the Poliquin Performance Center for elite athletes, says strength training is best done either three or 11 hours after you wake up, as this is when your strength levels are at their highest and your joints are most mobile. You can run early in the morning and do weight training later in the day.";

        public static string fish = @"Pour 2-inches of vegetable oil into a large skillet. Place skillet over large burner and heat oil over medium high heat. To check if the oil is hot enough, drop in 1-inch cube of white bread. The bread should brown in a 40 count.
Cut cod into 4 servings, 6 to 8-ounce portions and season with salt and pepper. Place a couple of scoops of flour in a pie tin. Combine egg and water in second tin. Season plain bread crumbs and mustard and cayenne in the third tin. Coat fish in flour, then egg, and then bread crumbs. Gently set coated fish into hot oil and fry 5 minutes on each side until medium golden brown in color.
When the fish is evenly golden all over, remove and drain on brown paper sacks.
Recipe courtesy of Rachael Ray";

        public static string swim = @"In the 1985 Ron Howard movie ""Cocoon,"" a group of elderly adults discovers that a nearby swimming pool has the power to imbue them with new strength, enhanced energy and a more youthful sense of well-being. While the cause of their new lease on life turns out to be from another planet, it doesn't take alien technology to reap the benefits of your neighborhood pool.
Even without the aid of mysterious otherworldly cocoons, regular swimming can offer anyone, especially older adults, a wide range of health benefits -- including feeling and looking younger.Here, we'll dive into the 10 ways taking to the water can boost your health.Swimming offers something no other aerobic exercise does: the ability to work your body without harsh impact to your skeletal system. When the human body is submerged in water, it automatically becomes lighter. When immersed to the waist, your body bears just 50 percent of its weight; dunk yourself to the chest and that number reduces to around 25 to 35 percent; with water all the way to the neck, you only have to bear 10 percent of your own weight. The other 90 percent is handled by the pool.
This means that the pool provides an ideal place to work stiff muscles and sore joints, especially if you're overweight or suffer from arthritis.
In its recommendation for the right types of exercise for people with arthritis, the Arthritis Foundation suggests those that stretch muscles, those that strengthen muscles, and those that provide an aerobic workout. A few laps in the pool combine all three!
If the pool is heated, so much the better for arthritis sufferers, as the warm water can help loosen stiff joints. In fact, people with rheumatoid arthritis receive greater benefits to their health after participating in hydrotherapy than with other activities. It's also been proven that water-based exercise improves the use of affected joints and decreases pain from osteoarthritis [source: CDC].";
    }
}
